name: Publish Development Build
on:
  push:
  workflow_dispatch:
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew --no-daemon test

      - name: Build with Gradle
        run: ./gradlew --no-daemon build -x test

      - name: Release
        if: github.ref_type == 'branch' && github.ref_name == github.event.repository.default_branch && github.actor != 'dependabot[bot]'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: snapshot
          name: Latest Build
          draft: false
          prerelease: false
          make_latest: true
          files: ./build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
